### PR TITLE
Update Consul to version 1.8.0

### PR DESCRIPTION
**Pull request by Kristjanf-droid**

### CODE REVIEW

**Comment by jonorri** [comment]
@calvn are there any issues with this PR?

**Comment by calvn** [comment]
No issues, I just have not gotten around to it yet. I'll merge and release shortly -- thanks for the PR!

Update: I'll likely release 1.7.3 and 1.7.4 before merging this.

**Comment by calvn** [comment]
@Kristjanf-droid can you resolve the conflicts from the version updates that happened since then?

**Comment by Kristjanf-droid** [comment]
Done

**Comment by calvn** [comment]
Sorry for asking once again, but can you resolve conflicts? I ended up releasing 1.7.5 and 1.7.6 just now. Currently waiting for 1.7.5 to be published before releasing 1.7.6, but we should be good if you merge from master.

**Pull request merged**
