### PR TITLE
Update consul to version 1.5.1

### PR DESCRIPTION
**Pull request by ids-pfinn**
Thanks for starting this chocolatey package!

### CODE REVIEW

**Comment by mahsoud** [comment]
anything blocking this version release?

**Comment by ids-pfinn** [comment]
@calvn Anything else we need to do to merge this in?

**Comment by calvn** [comment]
Sorry, I somehow missed this! I'll get this merged ASAP, but I'll also have to do releases on versions between 1.4.3 and 1.5.1 so that they are also available in chocolatey.

**Comment by calvn** [comment]
I've tried pushing 1.4.4 several times, but it seems that chocolatey is having trouble with it:
```
Attempting to push consul.1.4.4.nupkg to https://push.chocolatey.org/
Failed to process request. 'This package had an issue pushing: Exception of type 'System.OutOfMemoryException' was thrown.'. 
The remote server returned an error: (409) Conflict..
Command exited with code 1
```

There's [an open issue](https://github.com/chocolatey/chocolatey.org/issues/613) that reports on this same issue. I'll give it another try tomorrow morning.

**Comment by ids-pfinn** [comment]
👍 Thanks! Hope the choco issues is resolved soon.

**Comment by calvn** [comment]
Just gave it another try using chocolatey 0.10.15 and it's still failing, but now on a different error. I checked the package in chocolatey.org once logged in and there's no indication that 1.4.4 has been pushed up so I'm not sure what's going on with the registry.

```
Chocolatey v0.10.15
Attempting to push consul.1.4.4.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository.
Command exited with code 1
```

**Comment by mahsoud** [comment]
Try 1.4.5-test1 ?

**Comment by calvn** [comment]
@ids-pfinn I've released up to 1.5.0 (currently pending automated review) now that the registry is happy with my uploads. Can you resolve the conflicts to get this merged?

**Comment by ids-pfinn** [comment]
@calvn On it. Thanks!
Do you know what resolved the chocolatey issues you were seeing?

**Comment by calvn** [comment]
Not sure, I just kept trying over several days and it started to work last night. I've not changed anything code-wise or with the tag, and just kept rebuilding the tagged commit in CI until chocolatey was happy with the push.

**Comment by calvn** [comment]
I'll get this merged as soon as 1.5.0 is approved. Thanks!

**Comment by ids-pfinn** [comment]
👍

**Pull request merged**
