### PR TITLE
Update Consul to version 1.6.4

### PR DESCRIPTION
**Pull request by dylan-azucena**

### CODE REVIEW

**Comment by dylan-azucena** [comment]
@calvn can you merge this?

**Comment by calvn** [comment]
Thanks for the PR! I have also do the releases between the current one (1.6.1) and 1.6.4 before I can merge this. I'll get this merged once those are done.

**Comment by calvn** [comment]
Looks like chocolatey is rejecting the upload for 1.6.2 even after multiple attempts. I dropped a comment on a related issue, and currently awaiting their reply: https://github.com/chocolatey/chocolatey.org/issues/798

**Comment by calvn** [comment]
@dylan-azucena 1.6.2 got pushed and approved. I'm in the process of releasing 1.6.3 atm, can you update the branch to resolve the conflicts?

**Review by calvn — APPROVED** [review]

**Pull request merged**
