### PR TITLE
Update Consul to version 1.6.1

### PR DESCRIPTION
**Pull request by roback**

### CODE REVIEW

**Comment by jdebbink** [comment]
@calvn can you merge this?

**Comment by calvn** [comment]
Apologies for the delay. I'll need to release the versions prior to 1.6.1 before merging/release this one.

**Comment by roback** [comment]
I fixed the merge conflicts here @calvn

**Comment by calvn** [comment]
I am currently waiting for 1.6.0 to be pushed. There seems to be an issue on the chocolatey side that’s preventing it from being uploaded (I’ve encountered this in the past).

**Comment by calvn** [comment]
Just gave it another try and it was successfully pushed. Once 1.6.0 is released, I'll get this merged.

**Pull request merged**
