### PR TITLE
Updates Consul to v1.3.0

### PR DESCRIPTION
**Pull request by MagnumOpus21**
This PR updates the Chocolatey Package to the latest version v1.3.0.

### CODE REVIEW

**Comment by calvn** [comment]
Thanks! I'll hold on to merging/tagging this one until v1.2.3 gets approved on chocolatey, but LGTM!

**Comment by MagnumOpus21** [comment]
:tada:

**Comment by jage** [comment]
Bump, looks like 1.2.3 is approved? https://chocolatey.org/packages/consul/1.2.3

Cheers!

**Comment by calvn** [comment]
Yep, sorry this slipped!

**Comment by jage** [comment]
No worries, thanks!

**Pull request merged**
