### PR TITLE
Update to Consul version 1.0.7

### PR DESCRIPTION
**Pull request by jage**

### CODE REVIEW

**Comment by jage** [comment]
@calvn just let me know if there's anything else I can do to improve this PR. Thanks!

**Comment by calvn** [comment]
Hi there, thanks for the PR! I'll have to retroactively update the versions between 1.0.2 and 1.0.7 before I can merge this so that the other versions are available as well.

**Comment by calvn** [comment]
Master should be up to 1.0.6 now. Can you resolve the conflicts? :)

**Comment by jage** [comment]
> Master should be up to 1.0.6 now. Can you resolve the conflicts? :)

Great! Yes of course. :)

**Comment by jage** [comment]
Great work, thanks @calvn !

**Pull request merged**
