### PR TITLE
Update Consul to version 1.7.2

### PR DESCRIPTION
**Pull request by mahsoud**

### CODE REVIEW

**Comment by calvn** [comment]
Thanks for the PR! Unfortunately, I am currently blocked on releases due to chocolatey rejecting uploads. See https://github.com/calvn/chocolatey-consul/pull/43 for more detail.

**Comment by mahsoud** [comment]
gonna have to do something about it, 1.6.1 is getting too old ;)

**Comment by calvn** [comment]
Agreed. I've re-ran the build to push 1.6.2 numerous times, and just tried about 15 mins ago but no dice. Waiting for a response from the folks at chocolatey. I'll try to manually upload the package via the site tonight and see if that works.

**Comment by calvn** [comment]
I just gave manual update a try (or two) for choco-consul 1.6.2. The upload failed with a package size of ~78MB even though the upload limit is 200MB. 

Error from the site:
```
The page was not displayed because the request entity is too large.
```

**Pull request merged**
