### PR TITLE
Bump consul version to 1.0.2

### PR DESCRIPTION
**Pull request by hvindin**
Also updated the icon to the latest iteration.

### CODE REVIEW

**Comment by calvn** [comment]
Awesome, can you open a PR against 1.0.1 (with the icon change perhaps) to make that version available as well?

**Comment by hvindin** [comment]
I've created a seperate pull request for the jump from 1.0.0 -> 1.0.1 + the icon change. And have rebased this so that the change history looks logical (ie. 1.0.0 -> 1.0.1 -> 1.0.2) so this PR doesn't include the icon change except by virtue of being the subsequent commit to the 1.0.1 change.

**Comment by calvn** [comment]
Perfect, thanks a lot!

**Comment by calvn** [comment]
FYI 1.0.3 just got released today, if you want to do the honors of getting that as well :)

**Comment by hvindin** [comment]
Strange, looks like somehow the enterprise binaries where a few days late for 1.0.3, I only just got a notification from a watch that check's the enterprise s3 buckets every day for new versions. So I completely missed the release :/ Looks like 1.0.3 is in here so choco should work for the latest OSS version, which is a nice side effect of the tool, keeps me up to date 👍

**Pull request merged**
